spring.application.name=reservairbnb
spring.datasource.url=jdbc:postgresql://localhost:5432/reservairbnb_db
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASEÑA
spring.jpa.hibernate.ddl-auto=update
